fix(deps): Update dependency nl.jqno.equalsverifier:equalsverifier to v3.17.1 (#283)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [nl.jqno.equalsverifier:equalsverifier](https://www.jqno.nl/equalsverifier) ([source](https://togithub.com/jqno/equalsverifier)) | dependencies | patch | `3.17` -> `3.17.1` |

---

### Release Notes

<details>
<summary>jqno/equalsverifier (nl.jqno.equalsverifier:equalsverifier)</summary>

### [`v3.17.1`](https://togithub.com/jqno/equalsverifier/blob/HEAD/CHANGELOG.md#3171---2024-10-02)

##### Fixed

-   Instantiates `java.sql.Date` only when available, so EqualsVerifier no longer throws `NoClassDefFoundError` when it's not available (for instance, when running EqualsVerifier standalone instead of as part of a test suite). ([Issue 746](https://togithub.com/jqno/equalsverifier/issues/746))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy40NDAuNyIsInVwZGF0ZWRJblZlciI6IjM3LjQ0MC43IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJhdXRvbWVyZ2UiXX0=-->