fix(deps): Update dependency io.grpc:grpc-protobuf to v1.58.0 (#129)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [io.grpc:grpc-protobuf](https://togithub.com/grpc/grpc-java) | dependencies | minor | `1.57.2` -> `1.58.0` |

---

### Release Notes

<details>
<summary>grpc/grpc-java (io.grpc:grpc-protobuf)</summary>

### [`v1.58.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.58.0)

##### API Changes

-   xds: Add missing ExperimentalApi to OrcaServiceImpl
-   stub: Removed deprecated methods attachHeaders and captureMetadata from MetadataUtils ([#&#8203;10443](https://togithub.com/grpc/grpc-java/issues/10443))
-   api: Stabilized ServerCall.getAuthority() by removing experimental annotation ([#&#8203;10498](https://togithub.com/grpc/grpc-java/issues/10498))
-   api: Stabilized `ServerCall#setMessageCompression()` and `PartialForwardingServerCall#setMessageCompression()` ([#&#8203;10393](https://togithub.com/grpc/grpc-java/issues/10393))
-   protobuf: Stabilize `ProtoUtils.setExtensionRegistry()` and `ProtoLiteUtils.setExtensionRegistry()` ([#&#8203;10392](https://togithub.com/grpc/grpc-java/issues/10392))
-   testing: Stabilize `GrpcCleanupRule`, `GrpcServerRule` ([#&#8203;10494](https://togithub.com/grpc/grpc-java/issues/10494))
-   api: Stabilized ServerBuilder.handshakeTimeout ([#&#8203;10499](https://togithub.com/grpc/grpc-java/issues/10499))
-   api: Removed Context.Storage deprecated method attach(), made doAttach() abstract ([#&#8203;10379](https://togithub.com/grpc/grpc-java/issues/10379))
-   api : Stabilized methodDescriptor getRequestMarshaller, getResponseMarshaller ([#&#8203;10495](https://togithub.com/grpc/grpc-java/issues/10495))

##### Behavior Changes

-   rls: Have RLS's LRU Cache rely on cleanup process to remove expired entries ([#&#8203;10400](https://togithub.com/grpc/grpc-java/issues/10400))
-   core, inprocess, util: 2 new artifacts grpc-inprocess and grpc-util have been created by moving code from grpc-core to facilitate Java module support ([#&#8203;10362](https://togithub.com/grpc/grpc-java/issues/10362), [#&#8203;10390](https://togithub.com/grpc/grpc-java/issues/10390))
-   all: Automatic module name support added to all artifacts ([#&#8203;10413](https://togithub.com/grpc/grpc-java/issues/10413))
-   xds: Encode the service authority in XdsNameResolver ([#&#8203;10207](https://togithub.com/grpc/grpc-java/issues/10207))

##### Improvements

-   api: In Javadoc, link to gRFCs A8/A9 for keepalive and related settings
-   okhttp: Enable support for being returned by `Grpc.newServerBuilderForPort()`. At present, Netty always has higher priority than OkHttp, if they are both available, because `ServerBuilder.forPort()` is not supported in the OkHttp transport but is supported in the Netty transport
-   bazel: Enhance java_grpc_library.bzl to allow toolchain to use annotation processors
-   examples: Add pre-serialized-message example ([#&#8203;10112](https://togithub.com/grpc/grpc-java/issues/10112))
-   examples: Android examples to use AGP 7.4.0 ([#&#8203;10497](https://togithub.com/grpc/grpc-java/issues/10497))

##### Bug Fixes

-   Fix compatibility with Java 8. This fixes the `NoSuchMethodError` for `ByteBuffer` methods present in 1.57.0 ([#&#8203;10441](https://togithub.com/grpc/grpc-java/issues/10441))
-   xds: Remove debug assert in WeightedRoundRobinLoadBalancer. The assert was to detect breakages in the static stride algorithm causing too much looping. However, with multithreading it is possible to trigger even in legitimate scenarios ([#&#8203;10437](https://togithub.com/grpc/grpc-java/issues/10437))
-   util: Outlier detection tracer delegation ([#&#8203;10459](https://togithub.com/grpc/grpc-java/issues/10459))
-   Handle header with errors and endStream = true.  Was filling logs with NPEs. ([#&#8203;10384](https://togithub.com/grpc/grpc-java/issues/10384))
-   core: Fix a retriablestream bug that may cause deadlock with OkHttp ([#&#8203;10386](https://togithub.com/grpc/grpc-java/issues/10386))
-   stub: Remove ThreadlessExecutor from BlockingServerStream to eliminate the problem where sometimes the iterator’s next() method would get stuck. ([#&#8203;10496](https://togithub.com/grpc/grpc-java/issues/10496))
-   compiler: Fix aarch\_64 macs not being able to build the compiler module. ([#&#8203;10516](https://togithub.com/grpc/grpc-java/issues/10516))
-   okhttp: Use padded length for flow control in both client and server transport ([#&#8203;10422](https://togithub.com/grpc/grpc-java/issues/10422))
-   xds: Fix locality logging information in bootstrap ([#&#8203;10423](https://togithub.com/grpc/grpc-java/issues/10423))

##### Dependencies

-   Upgraded protobuf to 3.24.0
-   android: Min SDK level to 21 ([#&#8203;10505](https://togithub.com/grpc/grpc-java/issues/10505))
-   Various dependency upgrades ([#&#8203;10359](https://togithub.com/grpc/grpc-java/issues/10359)):
         androidx.core:core 1.10.0 -> 1.10.1
         com.google.api.grpc:proto-google-common-protos 2.17.0 -> 2.22.0
         com.google.cloud:google-cloud-logging 3.14.5 -> 3.15.5
         com.google.errorprone:error_prone_annotations 2.18.0 -> 2.20.0
         com.squareup.okio:okio 1.17.5 -> 2.10.0

##### Acknowledgements

Halvard Skogsrud

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4xMDkuNCIsInVwZGF0ZWRJblZlciI6IjM2LjEwOS40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->