fix(deps): Update dependency io.grpc:grpc-services to v1.57.1 (#11)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [io.grpc:grpc-services](https://togithub.com/grpc/grpc-java) | dependencies | patch | `1.57.0` -> `1.57.1` |

---

### Release Notes

<details>
<summary>grpc/grpc-java (io.grpc:grpc-services)</summary>

### [`v1.57.1`](https://togithub.com/grpc/grpc-java/releases/tag/v1.57.1)

### Bug fixes

-   Fix compatibility with Java 8. This fixes the `NoSuchMethodError` for `ByteBuffer` methods present in 1.57.0 ([#&#8203;10441](https://togithub.com/grpc/grpc-java/issues/10441))
-   xds: Remove debug assert in WeightedRoundRobinLoadBalancer. The assert was to detect breakages in the static stride algorithm causing too much looping. However, with multithreading it is possible to trigger even in legitimate scenarios ([#&#8203;10437](https://togithub.com/grpc/grpc-java/issues/10437))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [x] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4zNS4xIiwidXBkYXRlZEluVmVyIjoiMzYuMzUuMSIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->