fix(deps): Update dependency io.grpc:grpc-testing to v1.60.1 (#165)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [io.grpc:grpc-testing](https://togithub.com/grpc/grpc-java) | dependencies | minor | `1.57.2` -> `1.60.1` |

---

### Release Notes

<details>
<summary>grpc/grpc-java (io.grpc:grpc-testing)</summary>

### [`v1.60.1`](https://togithub.com/grpc/grpc-java/releases/tag/v1.60.1)

### Bug Fixes

-   util: Fix NPE when multiple addresses in an address group for petiole load balancer policies ([#&#8203;10770](https://togithub.com/grpc/grpc-java/issues/10770))

### [`v1.60.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.60.0)

##### API Changes

-   api: Stabilize `ForwardingServerBuilder`, `ForwardingChannelBuilder2`, and `ForwardingChannelBuilder`. Note that `ForwardingChannelBuilder` is stabilized (no changes will be made to it), but immediately deprecated in favor of `ForwardingChannelBuilder2`. ([#&#8203;10586](https://togithub.com/grpc/grpc-java/issues/10586))
-   api: Deprecate `ForwardingChannelBuilder.delegate()`. De facto this deprecates the class itself, since all classes extending `ForwardingChannelBuilder` implement the `delegate()` method. See javadoc for details ([#&#8203;10587](https://togithub.com/grpc/grpc-java/issues/10587))
-   api: Changed recently-introduced `LoadBalancer.acceptResolvedAddresses()` to return `Status` instead of `boolean` ([#&#8203;10636](https://togithub.com/grpc/grpc-java/issues/10636)). This is part of continued work to align the LB API cross-language and API stabilization
-   stub: Deprecate StreamObservers ([#&#8203;10654](https://togithub.com/grpc/grpc-java/issues/10654))
-   alts: AltsChannelBuilder now extends `ForwardingChannelBuilder2` ([#&#8203;10587](https://togithub.com/grpc/grpc-java/issues/10587))
-   protobuf: Stabilize `ProtoUtils.metadataMarshaller()` ([#&#8203;10628](https://togithub.com/grpc/grpc-java/issues/10628))
-   protobuf-lite: ProtoLiteUtils experimental comment ([#&#8203;10627](https://togithub.com/grpc/grpc-java/issues/10627))

##### Behavior Changes

-   core: `ManagedChannel`s now check the address types provided by the nameResolver (for the given target) with the address types supported by the channel transport and generate an error in case of mismatch. That dramatically improves the error message when an issue occurs
-   core: When a server stream is closed due to user's code (an uncaught exception in halfClosed, messagesAvailable, onReady callback of a ServerStream's listener), the `Status.UNKNOWN` returned to the client will have `Application error processing RPC` description. Previously the description was empty. This is helpful to differentiate between server errors originated in user application, gRPC library, or even those injected by a proxy. ([#&#8203;10643](https://togithub.com/grpc/grpc-java/issues/10643))
-   xds: Log ORCA UNIMPLEMENTED error to subchannel logger. This removes them from the normal application logs, reducing log spam

##### Improvements

-   Change the underlying implementations of RingHash, RoundRobin, WeightedRoundRobin and LeastRequest load balancers to utilize the pick first load balancer rather than directly manage subchannels. This should only be noticeable if it introduced a bug
-   core: Avoid flushing headers when the server returns a single response ([#&#8203;9314](https://togithub.com/grpc/grpc-java/issues/9314)). This is a performance optimization to reduce the number of packets for non-streaming responses
-   util: Make grpc-core an implementation dependency. This will prevent the io.grpc.internal classes in grpc-core from being visible during compilation when depending on just grpc-util
-   netty: Implement `Http2Headers.isEmpty()`. This fixes compatibility with Netty 4.1.101.Final.
-   netty: Add `NettyServerBuilder.maxRstFramesPerWindow()`. This can be used to limit impact of Rapid Reset
-   netty: Disable huffman coding in headers ([#&#8203;10563](https://togithub.com/grpc/grpc-java/issues/10563)). Huffman coding provides modest compression for relatively high CPU usage, especially within a data center. Rely just on the HPACK static and dynamic tables for compression, for higher performance. This only impacts header values 512 bytes or longer, as Netty already disabled Huffman for smaller values
-   alts: Improve handshake failure error message by propagating original exception ([#&#8203;10644](https://togithub.com/grpc/grpc-java/issues/10644))

##### Bug Fixes

-   util: Remove shutdown subchannels from OD tracking ([#&#8203;10683](https://togithub.com/grpc/grpc-java/issues/10683)). This could have caused a memory leak on a long-lived channel. But we don’t think it could be triggered with our built-in load balancing policies.

##### Dependencies

-   Bump Netty to 4.1.100.Final

##### Acknowledgements

[@&#8203;anthonyjpratti](https://togithub.com/anthonyjpratti)
[@&#8203;fedorka](https://togithub.com/fedorka)
[@&#8203;jpd236](https://togithub.com/jpd236)
[@&#8203;mateusazis](https://togithub.com/mateusazis)
[@&#8203;pkoenig10](https://togithub.com/pkoenig10)
[@&#8203;yannickepstein](https://togithub.com/yannickepstein)
[@&#8203;amirhadadi](https://togithub.com/amirhadadi)

### [`v1.59.1`](https://togithub.com/grpc/grpc-java/releases/tag/v1.59.1)

-   netty: Implement `Http2Headers.isEmpty()`. This fixes compatibility with Netty 4.1.101.Final.
-   netty: Add `NettyServerBuilder.maxRstFramesPerWindow()`. This can be used to limit impact of Rapid Reset
-   xds: Log ORCA UNIMPLEMENTED error to subchannel logger. This removes them from the normal application logs, reducing log spam

### [`v1.59.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.59.0)

#### gRPC Java 1.59.0 Release Notes

**PLANNED ABI BREAKAGE!**

This breaks the ABI of the `@ExperimentalApi` classes listed below.
This does not impact source code (API); it only impacts code compiled with a different version of gRPC than it runs with (ABI).

Users that recompiled their code using grpc-java [`v1.36.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.36.0) (released on Feb 23, 2021) and later, **ARE NOT AFFECTED**.
Users that compiled their source using grpc-java earlier than `v1.36.0` may need to recompile when upgrading to grpc-java `v1.59.0`.

See details in [#&#8203;10406](https://togithub.com/grpc/grpc-java/issues/10406).

**Affected classes**

Class `io.grpc.internal.AbstractManagedChannelImplBuilder` is deleted, and no longer in the class hierarchy of the channel builders:

-   `io.grpc.netty.NettyChannelBuilder`
-   `io.grpc.okhttp.OkhttpChannelBuilder`
-   `io.grpc.cronet.CronetChannelBuilder`

Class `io.grpc.internal.AbstractServerImplBuilder` is deleted, and no longer in the class hierarchy of the server builders:

-   `io.grpc.netty.NettyServerBuilder`
-   `io.grpc.inprocess.InProcessServerBuilder`

***

##### API Changes

-   core: `AbstractManagedChannelImplBuilder` and `AbstractServerImplBuilder` are removed ([#&#8203;10530](https://togithub.com/grpc/grpc-java/issues/10530)). This is ABI-breaking, see the warning above. ([#&#8203;10406](https://togithub.com/grpc/grpc-java/issues/10406))
-   core: Removed .class file hack previously introduced in [`v1.36.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.36.0) to ease removal of internal ABIs. ([#&#8203;10406](https://togithub.com/grpc/grpc-java/issues/10406))
-   api: Add `ForwardingChannelBuilder2`, an ABI-safe version of `ForwardingChannelBuilder`, which will be deprecated in the following release. ([#&#8203;10585](https://togithub.com/grpc/grpc-java/issues/10585), [#&#8203;10406](https://togithub.com/grpc/grpc-java/issues/10406))
-   api: Add `LoadBalancer.FixedResultPicker` convenience class for load balancer implementations. It is a replacement for `ErrorPicker` and `EMPTY_PICKER` added in 1.58.0
-   testing: Stabilize TestMethodDescriptors ([#&#8203;10530](https://togithub.com/grpc/grpc-java/issues/10530))

##### Behavior Changes

-   core: de-expermentalize pick first config parsing ([#&#8203;10531](https://togithub.com/grpc/grpc-java/issues/10531))
-   netty: Respect -Dio.netty.allocator.type=unpooled when getting Netty Allocator instead of ignoring it ([#&#8203;10543](https://togithub.com/grpc/grpc-java/issues/10543))
-   netty: Use UNAVAILABLE for connections closed while writing. Previously this would result in UNKNOWN
-   binder: Enable indirect addressing using <intent-filter>s. ([#&#8203;10550](https://togithub.com/grpc/grpc-java/issues/10550))

##### Improvements

-   core: only use reflection to resolve InternalCensusStatsAccessor once instead of once per channel
-   core: enhance error message in the case of DEADLINE_EXCEEDED to indicate name resolution delay.
-   netty: When creating a connection, use java.util.logging formatting instead of String.format to avoid work when not logged
-   netty: Touch ByteBuf when message framing has been decoded. If the buffer is leaked, this helps narrow down the source of reference counting bug
-   java_grpc_library.bzl: Disable Automatic Exec Groups inside grpc libraries ([#&#8203;10514](https://togithub.com/grpc/grpc-java/issues/10514)). This improves compatibility with future Bazel versions while retaining Bazel 5.x compatibility

##### Bug Fixes

-   netty: Avoid NettyAdaptiveCumulator incorrectly releasing its input ByteBuf twice when reading messages under certain error conditions ([#&#8203;10537](https://togithub.com/grpc/grpc-java/issues/10537))
-   xds: Add fix for xdstp replacement for percent-encoded authorities ([#&#8203;10571](https://togithub.com/grpc/grpc-java/issues/10571))

##### Documentation

-   API documentation (Javadoc) for Server and Channel builders now correctly displays inherited methods and the class hierarchy. ([#&#8203;10406](https://togithub.com/grpc/grpc-java/issues/10406))
-   examples: add an example for OAuth ([#&#8203;10560](https://togithub.com/grpc/grpc-java/issues/10560))

##### Dependencies

-   Upgrade Netty to 4.1.97.Final

##### Acknowledgements

John Cormie ([@&#8203;jdcormie](https://togithub.com/jdcormie))
Stephane Landelle ([@&#8203;slandelle](https://togithub.com/slandelle))
[@&#8203;kotlaja](https://togithub.com/kotlaja)

### [`v1.58.1`](https://togithub.com/grpc/grpc-java/releases/tag/v1.58.1)

-   xds:  PickFirst was not receiving its configuration so it used the default configuration which meant that randomize was ignored.

### [`v1.58.0`](https://togithub.com/grpc/grpc-java/releases/tag/v1.58.0)

##### API Changes

-   xds: Add missing ExperimentalApi to OrcaServiceImpl
-   stub: Removed deprecated methods attachHeaders and captureMetadata from MetadataUtils ([#&#8203;10443](https://togithub.com/grpc/grpc-java/issues/10443))
-   api: Stabilized ServerCall.getAuthority() by removing experimental annotation ([#&#8203;10498](https://togithub.com/grpc/grpc-java/issues/10498))
-   api: Stabilized `ServerCall#setMessageCompression()` and `PartialForwardingServerCall#setMessageCompression()` ([#&#8203;10393](https://togithub.com/grpc/grpc-java/issues/10393))
-   protobuf: Stabilize `ProtoUtils.setExtensionRegistry()` and `ProtoLiteUtils.setExtensionRegistry()` ([#&#8203;10392](https://togithub.com/grpc/grpc-java/issues/10392))
-   testing: Stabilize `GrpcCleanupRule`, `GrpcServerRule` ([#&#8203;10494](https://togithub.com/grpc/grpc-java/issues/10494))
-   api: Stabilized ServerBuilder.handshakeTimeout ([#&#8203;10499](https://togithub.com/grpc/grpc-java/issues/10499))
-   api: Removed Context.Storage deprecated method attach(), made doAttach() abstract ([#&#8203;10379](https://togithub.com/grpc/grpc-java/issues/10379))
-   api : Stabilized methodDescriptor getRequestMarshaller, getResponseMarshaller ([#&#8203;10495](https://togithub.com/grpc/grpc-java/issues/10495))

##### Behavior Changes

-   rls: Have RLS's LRU Cache rely on cleanup process to remove expired entries ([#&#8203;10400](https://togithub.com/grpc/grpc-java/issues/10400))
-   core, inprocess, util: 2 new artifacts grpc-inprocess and grpc-util have been created by moving code from grpc-core to facilitate Java module support ([#&#8203;10362](https://togithub.com/grpc/grpc-java/issues/10362), [#&#8203;10390](https://togithub.com/grpc/grpc-java/issues/10390))
-   all: Automatic module name support added to all artifacts ([#&#8203;10413](https://togithub.com/grpc/grpc-java/issues/10413))
-   xds: Encode the service authority in XdsNameResolver ([#&#8203;10207](https://togithub.com/grpc/grpc-java/issues/10207))

##### Improvements

-   api: In Javadoc, link to gRFCs A8/A9 for keepalive and related settings
-   okhttp: Enable support for being returned by `Grpc.newServerBuilderForPort()`. At present, Netty always has higher priority than OkHttp, if they are both available, because `ServerBuilder.forPort()` is not supported in the OkHttp transport but is supported in the Netty transport
-   bazel: Enhance java_grpc_library.bzl to allow toolchain to use annotation processors
-   examples: Add pre-serialized-message example ([#&#8203;10112](https://togithub.com/grpc/grpc-java/issues/10112))
-   examples: Android examples to use AGP 7.4.0 ([#&#8203;10497](https://togithub.com/grpc/grpc-java/issues/10497))

##### Bug Fixes

-   Fix compatibility with Java 8. This fixes the `NoSuchMethodError` for `ByteBuffer` methods present in 1.57.0 ([#&#8203;10441](https://togithub.com/grpc/grpc-java/issues/10441))
-   xds: Remove debug assert in WeightedRoundRobinLoadBalancer. The assert was to detect breakages in the static stride algorithm causing too much looping. However, with multithreading it is possible to trigger even in legitimate scenarios ([#&#8203;10437](https://togithub.com/grpc/grpc-java/issues/10437))
-   util: Outlier detection tracer delegation ([#&#8203;10459](https://togithub.com/grpc/grpc-java/issues/10459))
-   Handle header with errors and endStream = true.  Was filling logs with NPEs. ([#&#8203;10384](https://togithub.com/grpc/grpc-java/issues/10384))
-   core: Fix a retriablestream bug that may cause deadlock with OkHttp ([#&#8203;10386](https://togithub.com/grpc/grpc-java/issues/10386))
-   stub: Remove ThreadlessExecutor from BlockingServerStream to eliminate the problem where sometimes the iterator’s next() method would get stuck. ([#&#8203;10496](https://togithub.com/grpc/grpc-java/issues/10496))
-   compiler: Fix aarch\_64 macs not being able to build the compiler module. ([#&#8203;10516](https://togithub.com/grpc/grpc-java/issues/10516))
-   okhttp: Use padded length for flow control in both client and server transport ([#&#8203;10422](https://togithub.com/grpc/grpc-java/issues/10422))
-   xds: Fix locality logging information in bootstrap ([#&#8203;10423](https://togithub.com/grpc/grpc-java/issues/10423))

##### Dependencies

-   Upgraded protobuf to 3.24.0
-   android: Min SDK level to 21 ([#&#8203;10505](https://togithub.com/grpc/grpc-java/issues/10505))
-   Various dependency upgrades ([#&#8203;10359](https://togithub.com/grpc/grpc-java/issues/10359)):
         androidx.core:core 1.10.0 -> 1.10.1
         com.google.api.grpc:proto-google-common-protos 2.17.0 -> 2.22.0
         com.google.cloud:google-cloud-logging 3.14.5 -> 3.15.5
         com.google.errorprone:error_prone_annotations 2.18.0 -> 2.20.0
         com.squareup.okio:okio 1.17.5 -> 2.10.0

##### Acknowledgements

Halvard Skogsrud

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMTUuMCIsInVwZGF0ZWRJblZlciI6IjM3LjExNS4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->